services: sersan-api
buildOnMerge: true
build:
  - name: ssi
    args: [init-devstack, --build-only]
    id: 0
  - name: ssi
    args: [init, $services]
    id: 1
  - name: build
    args: [$services]
    env: [SS_GO_VERSION=1.10.2]
    id: 2
  - name: deploy
    graphSource: 2
    args: [sersan-api, -u, staging]
    id: 3
